In [ ]:
#Abdul Moiz
#200579
import numpy as np
import pandas as pd


In [ ]:
X1=np.array([2,4,6,15,30,60,80])
X2=np.array([1,2,7,6,11,14,70])
X3=np.array([3,8,20,4,60,30,13])
Y=np.array([1000,1300,1600,1100,900,3000,2700])

In [ ]:
c_X1=np.corrcoef(X1,Y)
c_X2=np.corrcoef(X2,Y)
c_X3=np.corrcoef(X3,Y)
print(c_X1)
print(c_X2)
print(c_X3)

[[1.         0.83041978]
 [0.83041978 1.        ]]
[[1.         0.63176401]
 [0.63176401 1.        ]]
[[1.         0.00208413]
 [0.00208413 1.        ]]


In [ ]:
mean.X1=np.mean(X1)
mean.X2=np.mean(X2)
mean.X3=np.mean(X3)

meany=np.mean(Y)

In [ ]:
st_X1=np.std(X1)
st_X2=np.std(X2)
st_X3=np.std(X3)
st_Y=np.std(Y)

In [ ]:
AB=(st_X1-meany)/(st_X1-st_Y)
print(AB)

2.1466027370096654


In [ ]:
B=(st_X2-meany)/(std_X2-std_Y)
print(B)

2.1378043801587783


In [ ]:
C=(st_X3-meany)/(st_X3-std_Y)
print(C)

2.1321046567882034
